### PR TITLE
Metaclass dynamic remapping

### PR DESCRIPTION
**Pull request by lukebemish**
Still work in progress, as I have yet to implement a few things. Does remapping of names at runtime using a metaclass factory. Currently works with methods called normally; I need to do some more work to get MetaProperties and the like functional.

### CODE REVIEW

**Comment by lukebemish** [comment]
Everything, including stuff like MetaProperties, should be working now. I'm going to go through and do some cleanup.

**Comment by lukebemish** [comment]
Going to mark this as "ready for review", since I think I've fixed the most glaring issues, but I'll probably go over it for any smaller stuff I've missed tomorrow.

**Comment by PaintNinja** [comment]
Had a quick scan read through it and it LGTM, only thing I would really change is the null checks - in Groovy, `==` and `!=` are roughly equivalent to Java's `obj.equals()` and `!obj.equals()` respectively to make stuff like String comparisons easier. When checking against `null`, it's faster to do `===`  and `!==` instead. ;)

Nice job managing to pull this off so quickly btw!

**Comment by lukebemish** [comment]
Thank you! I've thought up a few more edge cases for stuff, and want to do some more testing, so I'll change those equality checks while I'm at it

**Comment by lukebemish** [comment]
Note: this is not quite ready to go. I need to test some stuff with inheritance. I'll leave another comment and possibly some fixes once I've done that

**Comment by lukebemish** [comment]
I did some testing, and you may want to do more, but that *should* allow inherited fields/methods/whatever to be found correctly, and allow the MetaClass factory to correctly target classes extending from vanilla classes.

**Pull request merged**
